import * as pdfjs from './vendor/pdf.min.mjs';
import {parseInvoice,markDuplicates,makeCSV} from './parser.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.min.mjs',import.meta.url).href;
const $=id=>document.getElementById(id);let records=[],selected=-1,renderJob=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=(n,currency='')=>n===null||n===undefined?'Not extracted':Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+(currency?' '+currency:'');
async function readPDF(bytes,name){
 let doc=await pdfjs.getDocument({data:bytes.slice()}).promise;if(doc.numPages>30)throw new Error('More than 30 pages');let lines=[];
 for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),content=await page.getTextContent();let groups=new Map();for(const item of content.items){if(!('str'in item))continue;const y=Math.round(item.transform[5]*2)/2;groups.set(y,[...(groups.get(y)||[]),item]);}for(const [y,items]of [...groups].sort((a,b)=>b[0]-a[0]))lines.push(items.sort((a,b)=>a.transform[4]-b.transform[4]).map(x=>x.str).join(' ').trim());}
 return {doc,text:lines.join('\n')};
}
async function process(files){
 $('samples').disabled=true;$('files').disabled=true;$('export').disabled=true;$('csv-ready').hidden=true;records=[];
 try{for(const [i,file]of files.entries()){$('progress').textContent=`Reading PDF ${i+1} of ${files.length}…`;try{const bytes=file.bytes||new Uint8Array(await file.arrayBuffer());if(bytes.length>20*1024*1024)throw new Error('File exceeds 20 MB');const {doc,text}=await readPDF(bytes,file.name);records.push({...parseInvoice(text,file.name),doc,bytes});}catch(e){records.push({source_file:file.name,vendor:'',invoice_number:'',date:'',currency:'',items:[],review_required:true,review_reasons:['PDF could not be read: '+e.message]});}}
 markDuplicates(records);const count=records.filter(x=>x.review_required).length;$('progress').textContent=`${records.length} invoices · ${count} need review`;$('filter').value='all';list();if(records.length)await select(0);$('export').disabled=!records.length;
 }finally{$('samples').disabled=false;$('files').disabled=false;}
}
function list(){const mode=$('filter').value;$('invoice-list').innerHTML=records.map((r,i)=>{if(mode==='review'&&!r.review_required||mode==='matched'&&r.review_required)return '';return `<button class="invoice ${i===selected?'active':''}" data-index="${i}"><strong>${esc(r.invoice_number||r.source_file)}</strong><small>${esc(r.vendor||'Extraction needs review')}</small><span class="label ${r.review_required?'review':''}">${r.review_required?'Needs review':'Reconciled'}</span></button>`;}).join('')||'<p class="empty">No invoices match this filter.</p>';for(const b of $('invoice-list').querySelectorAll('button'))b.addEventListener('click',()=>select(Number(b.dataset.index)));}
async function select(index){
 selected=index;list();const r=records[index];$('document-name').textContent=r.source_file;
 $('fields').innerHTML=`<dl><dt>Vendor</dt><dd>${esc(r.vendor||'Not extracted')}</dd><dt>Invoice number</dt><dd>${esc(r.invoice_number||'Not extracted')}</dd><dt>Date</dt><dd>${esc(r.date||'Not extracted')}</dd><dt>Currency</dt><dd>${esc(r.currency||'Not extracted')}</dd></dl><div><div class="balance">${[['Line items',r.items_sum],['Tax',r.tax],['Shipping',r.shipping],['Discount',r.discount],['Calculated total',r.expected_total],['Printed total',r.invoice_total],['Difference',r.difference]].map(([k,v])=>`<div class="${k==='Difference'?'grand':''}"><span>${k}</span><span>${esc(amount(v,k==='Printed total'?r.currency:''))}</span></div>`).join('')}</div>${r.review_required?`<div class="review-note"><strong>Manual review</strong><br>${r.review_reasons.map(esc).join('<br>')}</div>`:'<p class="success-note">Printed total reconciles with the extracted values.</p>'}</div>`;
 $('lines').innerHTML=r.items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.quantity)}</td><td>${esc(amount(x.unit_price))}</td><td>${esc(amount(x.amount))}</td><td>${esc(amount(x.quantity!==null&&x.unit_price!==null?x.quantity*x.unit_price:null))}</td></tr>`).join('')||'<tr><td colspan="5">No line items extracted. Review the original document.</td></tr>';
 if(renderJob){renderJob.cancel();renderJob=null;}const canvas=$('pdf-canvas');if(r.doc){$('placeholder').hidden=true;canvas.hidden=false;const page=await r.doc.getPage(1);if(index!==selected)return;const viewport=page.getViewport({scale:1.2});canvas.width=viewport.width;canvas.height=viewport.height;renderJob=page.render({canvasContext:canvas.getContext('2d'),viewport});try{await renderJob.promise;}catch(e){if(e.name!=='RenderingCancelledException')throw e;}renderJob=null;const old=$('open-pdf').href;if(old.startsWith('blob:'))URL.revokeObjectURL(old);$('open-pdf').href=URL.createObjectURL(new Blob([r.bytes],{type:'application/pdf'}));$('open-pdf').hidden=false;}else{canvas.hidden=true;$('placeholder').hidden=false;$('open-pdf').hidden=true;}
}
$('samples').addEventListener('click',async()=>{try{const names=['01_standard.pdf','02_with_tax.pdf','03_shipping.pdf','04_discount.pdf','05_decimal_comma.pdf','06_large_amount.pdf','07_total_mismatch.pdf','08_line_mismatch.pdf','09_missing_date.pdf','10_scanned.pdf'];const files=[];for(const name of names){const response=await fetch('inputs/'+name);if(!response.ok)throw new Error('Sample unavailable: '+name);files.push({name,bytes:new Uint8Array(await response.arrayBuffer())});}await process(files);}catch(e){$('progress').textContent='Could not process samples: '+e.message;}});
$('files').addEventListener('change',async()=>{if($('files').files.length)await process([...$('files').files]);});$('filter').addEventListener('change',list);
$('export').addEventListener('click',()=>{const a=$('csv-ready');if(a.href.startsWith('blob:'))URL.revokeObjectURL(a.href);a.href=URL.createObjectURL(new Blob([makeCSV(records)],{type:'text/csv;charset=utf-8'}));a.hidden=false;a.click();});
